### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by unclesam87** [nextcloud/external#45] opened 2017-06-27 09:32 UTC
### Steps to reproduce
1. add Site
2. try to click on it
3. wait for nothing to happen

### Expected behaviour
 Site should open (One of the Sites lays on the same server, but is managed per vhost, one of the sites is only avaibel per https, the third is a pretty normal website)

### Actual behaviour
noting happens
### Server configuration

**Operating system**:Ubuntu 16.04 LTS

**Web server:** LAMP

**Database:** mysql2

**PHP version:** 7.0.18-0.ubuntu0.16.04.01

**Nextcloud version:**12

**Where did you install Nextcloud from:** 

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - deck: 0.2.0
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.4
  - files_automatedtagging: 1.2.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - groupfolders: 1.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.4
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - richdocuments: 1.12.33
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

### Client configuration
**Browser:**
Firefox
Google Chrome
**Operating system:**
Arch Linux
### Logs

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by nickvergessen** [comment] 2017-06-27 16:46
Can you check your browsers console (F12) whether it shows some errors?

**Comment by unclesam87** [comment] 2017-06-29 09:26
**First Website**
about:blank:1 Mixed Content: The page at 'https://subdomain.maindomain.de/index.php/apps/external/2' was loaded over HTTPS, but requested an insecure resource 'http://subdomain2.maindomain.de/'. This request has been blocked; the content must be served over HTTPS.
**Second Website**
Mixed Content: The page at 'https://subdomain.maindomain.de/index.php/apps/external/3' was loaded over HTTPS, but requested an insecure resource 'http://www.maindomain.de/user'. This request has been blocked; the content must be served over HTTPS.
**Third Website**
JQMIGRATE: Migrate is installed, version 1.4.0
1:1 Refused to display 'https://www.werk21system.de/roundcube/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
1:400 GET https://www.werk21system.de/roundcube/ net::ERR_BLOCKED_BY_RESPONSE

**Comment by nickvergessen** [comment] 2017-06-29 10:07
See https://docs.nextcloud.com/server/12/admin_manual/configuration_server/external_sites.html#configurations-preventing-embedding

it mentions both your problems:
1. http can not be embedded on https
2. sameorigin must be used

But you can do both in the future. For Nextcloud 13 I added an option ( PR: #43 ), so instead of embedding the links can redirect. Then http and sameorigin are no problems anymore.

So this is a duplicate of #27

**Closed by nickvergessen** 2017-06-29 10:07 UTC
Labels: needs info
