### ISSUE TITLE
Adding the Option open in a New Tab for each sites

### ISSUE THREAD

**Issue by JSChasle** [nextcloud/external#475] opened 2023-05-05 01:34 UTC
More a request could an option of "Open in new tab" or a behavior like "_blank" be added. As many of the external site must be in "This site must not be embeded"
Thanks,

**Comment by provokateurin** [comment] 2023-08-21 08:13
Duplicate of https://github.com/nextcloud/external/issues/79

**Closed by provokateurin** 2023-08-21 08:13 UTC
