### ISSUE TITLE
Multiple quota links

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/external#34] opened 2017-05-29 12:53 UTC
For example:

- Button 1 `Buy more storage`
- Button 2  `Edit your personal Settings` (For LDAP management UI)

You are currently able to create multiple quota links, but only one will be shown. Under the quota bar is enough space to show multiple buttons.

What do you think? @nickvergessen

**Comment by nickvergessen** [comment] 2017-05-29 15:21
Yeah currently it is hacked for one quota link, since that was a requirement....

**Comment by nickvergessen** [comment] 2017-05-29 15:22
Also this is used on the mobile apps as a “click on quota bar“ action. So more then one may cause unexpected behaviour

**Comment by wiswedel** [comment] 2019-12-02 20:48
The here initially described behavior is exactly back with 3.4.1 on Nextcloud 17.0.1

**Comment by wiswedel** [comment] 2019-12-02 20:49
CC @nickvergessen as agreed in https://github.com/nextcloud/external/pull/38#issuecomment-557077226

**Comment by nickvergessen** [comment] 2019-12-02 21:42
"Create a new issue"
- Reopens issue that was solved more than 2 years ago

**Comment by wiswedel** [comment] 2019-12-02 21:50
> "Create a new issue"
> 
>     * Reopens issue that was solved more than 2 years ago

I don't understand what's wrong about that. The user story is exactly the same as 2 years ago, the description matches 100% - that's what "re-open" means in my opinion.

**Comment by nickvergessen** [comment] 2019-12-03 16:22
Moved to https://github.com/nextcloud/external/issues/173

> I don't understand what's wrong about that. 

This is a bug tracker, not a user story collection ;)
It's all about being able to reproduce the flow later on to see which ticket was fixed by which commit etc. Having a ticket fixed by multiple commits at the same time is just confusing.

**Closed by nickvergessen** 2019-12-03 16:22 UTC
Labels: bug
