### ISSUE TITLE
Open a web page in a new tab instead of embedding it in Nextcloud

### ISSUE THREAD

**Issue by K-Hoffmann** [nextcloud/external#116] opened 2018-08-07 15:52 UTC
A useful option would be for us to be able to open an external link in a new tab by default instead of having to press Ctrl. The background: we link to an external application that only functions to a limited extent within the Nextcloud application.

For example, an additional checkbox:

(x) Open link in new tab

Is it difficult to implement the feature? Can you put that on your lists of advanced options?

Thanks in advance.

**Comment by nickvergessen** [comment] 2018-08-07 16:36
Duplicate of #79, #86, #92, #93, #99 and #101

**Closed by nickvergessen** 2018-08-07 16:36 UTC

**Comment by nooblag** [comment] 2021-06-17 16:19
Since many people are asking for this functionality (i.e. above duplicate of #79, #86, #92, #93, #99 and #101) why is this not being implemented? 

Surely it's not too difficult to provide something like this:

![ExternalSites](https://user-images.githubusercontent.com/1122344/122435682-8caf0580-cfdb-11eb-86ef-0c4c6d1b7729.PNG)

**Comment by nickvergessen** [comment] 2021-06-17 18:52
https://github.com/nextcloud/external/issues/79
