### ISSUE TITLE
No opens local link from nextcloud

### ISSUE THREAD

**Issue by ion-lane** [nextcloud/external#139] opened 2019-05-03 13:47 UTC
Hi,
On the nextcloud server, I created a second website [dokuwiki](https://www.dokuwiki.org/) on port 8443.
Dokuwiki perfectly worked locally on the server nextcloud through External sites.
But from the Internet site through nextcloud not open because port 8443 is not opened to the Internet.
It turns out that if I go to the nextcloud from the phone and try to open the site through an external sites, then it opens through the phone and not through the nectxloud.

Nextcloud: 15.0.7
External sites:3.2.0

**Comment by nickvergessen** [comment] 2019-05-03 17:39
Duplicate of  #12 #62 #72 and #128

**Closed by nickvergessen** 2019-05-03 17:39 UTC
