### ISSUE TITLE
Show entries immediately in menu after configuring

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/external#28] opened 2017-05-12 15:30 UTC
* currently you need to reload the page when configure a menu entry
* it should be the same as with enabling apps: after setting it up it should be added to the menu
* from nextcloud/server#2672

**Comment by nickvergessen** [comment] 2017-05-13 10:02
See #11 and #19 

Only doesn't work for the settings menu atm, caused by reasons out of scope of this app.

**Closed by nickvergessen** 2017-05-13 10:02 UTC
Labels: design, enhancement, papercut
