### ISSUE TITLE
Feature Request: Add per-user settings

### ISSUE THREAD

**Issue by zaphbbrox** [nextcloud/external#141] opened 2019-06-25 11:41 UTC
Hey folks,

first of all thanks for your work!
This is not a bug report more like a feature request.

Would it be possible to add per-user settings?
For example:
I currently have an external site for bicycle routing and the URL sets the starting point to my home address. Of course other users would like to do the same.
 As far as I understand right now I would have to add a external site and set it to an equivalent group. But I don't want to have the trouble to set a special group for every user which wants to have custom URL of the same site.
I'm thinking of something like: The admin sets a site and the users can change this URL.

**Example**: 
admin sets site *http://finnder.org* and the user can change it to *http://finnder.org/de-berlin#/!/2/1/52.51865,13.3761/-,-* to set their starting point to *Platz der Republik 1, 10557 Berlin*.

If you don't think it's practical feel free to close the issue.

**Comment by nickvergessen** [comment] 2019-09-03 09:40
Duplicate of #82

**Closed by nickvergessen** 2019-09-03 09:40 UTC
Labels: enhancement
