### ISSUE TITLE
Add please separation of users

### ISSUE THREAD

**Issue by DeAlexPesh** [nextcloud/external#59] opened 2017-10-06 05:05 UTC
Thank you for app, but can you add user separation for link (by groups) ?

**Nextcloud 12.0.3**

**Comment by nickvergessen** [comment] 2017-10-06 06:45
Duplicate of #26
Groups will come with Nextcloud 13

**Closed by nickvergessen** 2017-10-06 06:45 UTC

**Comment by DeAlexPesh** [comment] 2017-10-06 06:49
In stable version groups no work?

**Comment by nickvergessen** [comment] 2017-10-06 08:27
It will work in the next stable version: Nextcloud 13

**Comment by DeAlexPesh** [comment] 2017-10-06 10:20
ok, wait for release of a stable version of the nextcloud 13..
