### ISSUE TITLE
Config dont loading

### ISSUE THREAD

**Issue by Erebus999** [nextcloud/external#220] opened 2020-10-20 11:15 UTC
Config side dont loading.
I see only one round waiting circle.

How can I delete all the settings?
Unfortunately, deleting and reinstalling the app does not help.

**Comment by nickvergessen** [comment] 2020-10-20 11:40
Duplicate of #217

**Comment by nickvergessen** [comment] 2020-10-20 13:16
So if this happens for you also with the last 3.7.1 version, please open the browser console (F12) and check for errors there.

**Comment by Erebus999** [comment] 2020-10-20 14:30
![image](https://user-images.githubusercontent.com/34164477/96600764-9586f480-12f1-11eb-81a3-a91f9eb14c42.png)

**Comment by Erebus999** [comment] 2020-10-20 14:38
ie @ globals.js:60
script.js?v=05e035c4-22:113 Uncaught TypeError: $(...).tipsy is not a function
    at HTMLDocument.<anonymous> (script.js?v=05e035c4-22:113)
    at l (jquery.js:3187)
    at Object.fireWith [as resolveWith] (jquery.js:3317)
    at ready (jquery.js:3536)

**Comment by Erebus999** [comment] 2020-10-20 14:43
Thanks for reopening.
I have now found the error through the log with F12.
Nextbackup is causing a problem.
After deactivating NextBackup, the config page works.
Thanks for the support.

**Comment by nickvergessen** [comment] 2020-10-20 15:21
Glad to hear. Please let the developer of NextBackup know about the issue!

**Closed by nickvergessen** 2020-10-20 15:21 UTC
