### ISSUE TITLE
Feature Request: ID should be a GUID

### ISSUE THREAD

**Issue by rogeriovazp** [nextcloud/external#180] opened 2020-02-07 21:23 UTC
I think it's very cool that you can somehow restrict access to a external site by just setting the group for it. But nowadays it's fairly easy for a user to guess and get access to external sites he is not supposed to. 

I.E: Suppose you have 10 external sites and you want the user A to have access just to the first one you created. That external site probably will have a id 1 and it's URL will be something like: https://nextcloudsite.com/apps/external/1.

That way it´s for the user to guess the other external sites by just increasing the ID.

If the ID of the external site was a GUID it would be very hard for the user to guess the URL to access.

**Comment by nickvergessen** [comment] 2020-02-07 21:46
Duplicate of #136

**Closed by nickvergessen** 2020-02-07 21:46 UTC
